import os, json, datetime
import boto3
from common.bedrock_claude import claude_summarize

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

ddb = boto3.client("dynamodb")
s3  = boto3.client("s3")

TENANTS_TABLE   = os.environ["TENANTS_TABLE"]
INSIGHTS_BUCKET = os.environ["INSIGHTS_BUCKET"]
EVIDENCE_BUCKET = os.environ["EVIDENCE_BUCKET"]

def _tenant_ids():
    resp = ddb.scan(TableName=TENANTS_TABLE, ProjectionExpression="tenant_id")
    return [i["tenant_id"]["S"] for i in resp.get("Items", [])]

def _get_latest_insights(tenant_id: str) -> dict | None:
    key = f"{tenant_id}/latest.json"
    try:
        obj = s3.get_object(Bucket=INSIGHTS_BUCKET, Key=key)
        return json.loads(obj["Body"].read())
    except Exception:
        return None

def _render_html(tenant_id: str, day: str, snapshot: dict, brief: dict, raw_model_output: str) -> str:
    bullets = "".join([f"<li>{b}</li>" for b in (brief.get("summary_bullets") or [])])
    anomalies = "".join([f"<li>{a}</li>" for a in (brief.get("anomalies") or [])])
    actions = "".join([f"<li>{a}</li>" for a in (brief.get("next_actions") or [])])

    return f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>ValueOS Evidence Pack - {tenant_id} - {day}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Arial, sans-serif; margin: 40px; }}
    .hdr {{ display:flex; justify-content:space-between; align-items:flex-end; border-bottom:1px solid #ddd; padding-bottom:10px; }}
    .kpi {{ display:flex; gap:16px; margin-top:16px; flex-wrap: wrap; }}
    .card {{ border:1px solid #eee; border-radius:10px; padding:12px 14px; min-width:160px; }}
    h2 {{ margin-top:24px; }}
    pre {{ background:#f7f7f7; padding:12px; border-radius:10px; overflow:auto; }}
  </style>
</head>
<body>
  <div class="hdr">
    <div>
      <h1>ValueOS Evidence Pack</h1>
      <div><b>Tenant:</b> {tenant_id}</div>
      <div><b>Date:</b> {day}</div>
    </div>
    <div style="text-align:right;">
      <div><b>Confidence:</b> {brief.get("confidence", "")}</div>
      <div style="color:#666;">Generated by Bedrock Claude</div>
    </div>
  </div>

  <div class="kpi">
    <div class="card"><b>AI Runs</b><div>{snapshot.get("ai_runs", 0)}</div></div>
    <div class="card"><b>Outcomes</b><div>{snapshot.get("outcomes", 0)}</div></div>
    <div class="card"><b>Attributed</b><div>{snapshot.get("attributed_outcomes", 0)}</div></div>
    <div class="card"><b>Cost (USD)</b><div>{snapshot.get("cost_usd", 0)}</div></div>
    <div class="card"><b>Latency (ms)</b><div>{snapshot.get("latency_ms", 0)}</div></div>
  </div>

  <h2>Executive Summary</h2>
  <ul>{bullets}</ul>

  <h2>Anomalies</h2>
  <ul>{anomalies}</ul>

  <h2>Next Actions (7 days)</h2>
  <ul>{actions}</ul>

  <h2>Evidence Snapshot</h2>
  <pre>{json.dumps(snapshot, indent=2)}</pre>

  <h2>Model Output (raw)</h2>
  <pre>{raw_model_output}</pre>
</body>
</html>
"""

def _render_pdf(path: str, tenant_id: str, day: str, snapshot: dict, brief: dict):
    c = canvas.Canvas(path, pagesize=letter)
    width, height = letter
    x = 0.8 * inch
    y = height - 0.8 * inch

    def line(txt, dy=14):
        nonlocal y
        c.drawString(x, y, txt[:120])
        y -= dy
        if y < 1.0*inch:
            c.showPage()
            y = height - 0.8*inch

    c.setFont("Helvetica-Bold", 16)
    line(f"ValueOS Evidence Pack — {tenant_id}", 20)
    c.setFont("Helvetica", 11)
    line(f"Date: {day}")
    line("")

    c.setFont("Helvetica-Bold", 12)
    line("Key Metrics", 16)
    c.setFont("Helvetica", 11)
    line(f"AI Runs: {snapshot.get('ai_runs', 0)}")
    line(f"Outcomes: {snapshot.get('outcomes', 0)}")
    line(f"Attributed Outcomes: {snapshot.get('attributed_outcomes', 0)}")
    line(f"Cost (USD): {snapshot.get('cost_usd', 0)}")
    line(f"Latency (ms): {snapshot.get('latency_ms', 0)}")
    line("")

    c.setFont("Helvetica-Bold", 12)
    line("Executive Summary", 16)
    c.setFont("Helvetica", 11)
    for b in (brief.get("summary_bullets") or [])[:8]:
        line(f"• {b}", 14)
    line("")

    c.setFont("Helvetica-Bold", 12)
    line("Anomalies", 16)
    c.setFont("Helvetica", 11)
    for a in (brief.get("anomalies") or [])[:6]:
        line(f"• {a}", 14)
    line("")

    c.setFont("Helvetica-Bold", 12)
    line("Next Actions (7 days)", 16)
    c.setFont("Helvetica", 11)
    for a in (brief.get("next_actions") or [])[:8]:
        line(f"• {a}", 14)

    c.save()

def handler(event, context):
    today = datetime.datetime.utcnow().strftime("%Y%m%d")
    only_tenant = event.get("tenant_id") if isinstance(event, dict) else None
    tenants = [only_tenant] if only_tenant else _tenant_ids()

    for tenant_id in tenants:
        if not tenant_id:
            continue
        latest = _get_latest_insights(tenant_id)
        if not latest:
            continue

        snapshot = latest.get("snapshot") or {}
        raw_model_output = latest.get("model_output") or ""

        prompt = f"""
Create a concise 1-page evidence pack brief for a CFO/COO.
Return strict JSON only with:
- summary_bullets (max 6)
- anomalies (max 3)
- value_signals (max 4)
- next_actions (max 5)
- confidence (0..1)
Snapshot: {json.dumps(snapshot)}
RawModelOutput: {raw_model_output[:6000]}
"""
        text = claude_summarize(
            system="You output strict JSON only. No commentary.",
            user=prompt,
            max_tokens=650
        )

        try:
            brief = json.loads(text)
        except Exception:
            brief = {"summary_bullets": [], "anomalies": [], "next_actions": [], "confidence": 0.3}

        html = _render_html(tenant_id, today, snapshot, brief, raw_model_output)

        html_key = f"{tenant_id}/{today}/evidence.html"
        pdf_key  = f"{tenant_id}/{today}/evidence.pdf"
        latest_html_key = f"{tenant_id}/latest.html"
        latest_pdf_key  = f"{tenant_id}/latest.pdf"

        s3.put_object(Bucket=EVIDENCE_BUCKET, Key=html_key, Body=html.encode("utf-8"), ContentType="text/html")
        s3.put_object(Bucket=EVIDENCE_BUCKET, Key=latest_html_key, Body=html.encode("utf-8"), ContentType="text/html")

        pdf_path = f"/tmp/{tenant_id}-{today}.pdf"
        _render_pdf(pdf_path, tenant_id, today, snapshot, brief)

        with open(pdf_path, "rb") as f:
            s3.put_object(Bucket=EVIDENCE_BUCKET, Key=pdf_key, Body=f.read(), ContentType="application/pdf")
        with open(pdf_path, "rb") as f:
            s3.put_object(Bucket=EVIDENCE_BUCKET, Key=latest_pdf_key, Body=f.read(), ContentType="application/pdf")

    return {"statusCode": 200, "body": "ok"}
